- nextjs/components/Channel/Channel.tsx
- nextjs/components/Channel/Empty/index.module.css
- nextjs/components/Channel/Empty/index.tsx
- nextjs/components/Channel/index.module.css
- nextjs/components/MessageForm/index.tsx
- nextjs/components/Thread/Thread.tsx
> Empty channel

- nextjs/components/Channel/Channel.tsx
- nextjs/components/Channel/Empty/index.module.css
- nextjs/components/Channel/index.module.css
- nextjs/components/layout/shared/ChatLayout/index.module.css
- nextjs/components/layout/shared/ChatLayout/index.tsx
> Add a ChatLayout

- nextjs/components/Avatar/index.module.scss
- nextjs/components/Avatar/index.tsx
- nextjs/components/Channel/Channel.tsx
- nextjs/components/Channel/ChannelForBots.tsx
- nextjs/components/Channel/ChannelGrid/index.tsx
- nextjs/components/Channel/ChannelRow/index.tsx
- nextjs/components/Feed/index.tsx
- nextjs/components/Message/Row/index.module.scss
- nextjs/components/Message/Row/index.tsx
- nextjs/components/MessageCard/index.tsx
- nextjs/components/Thread/Header/Title/index.tsx
- nextjs/components/icons/CheckIcon/index.module.scss
- nextjs/components/icons/CheckIcon/index.tsx
- nextjs/components/icons/LinenIcon/index.module.scss
- nextjs/styles/colors.scss
> Improvements

- nextjs/components/Channel/Empty/index.module.css
- nextjs/components/Channel/Empty/index.tsx
- nextjs/components/icons/CheckIcon/index.module.scss
> Minor ux improvements

- nextjs/components/Link/InternalLink.tsx
- nextjs/components/NavBar/Desktop/NavLabel/index.module.scss
- nextjs/components/NavBar/Desktop/index.tsx
- nextjs/hooks/path.tsx
> Check feed active state

- nextjs/components/Channel/Channel.tsx
- nextjs/components/Channel/Header/index.module.css
- nextjs/components/Channel/Header/index.tsx
- nextjs/components/StickyHeader/index.module.scss
- nextjs/components/StickyHeader/index.tsx
- nextjs/components/Thread/Header/index.tsx
> Sticky header in the channel view

- nextjs/components/Channel/Channel.tsx
- nextjs/components/Channel/ChannelForBots.tsx
- nextjs/components/Channel/ChannelGrid/index.module.scss
- nextjs/components/Channel/ChannelGrid/index.tsx
- nextjs/components/Channel/Header/index.tsx
- nextjs/components/Channel/PinnedThread/index.module.scss
- nextjs/components/Channel/PinnedThread/index.tsx
- nextjs/components/NavBar/Desktop/index.tsx
- nextjs/components/Pages/ChannelsPage/ChannelPage.tsx
- nextjs/components/Pages/ChannelsPage/index.tsx
- nextjs/components/Pages/Feed/Filters/index.module.css
- nextjs/components/Pages/Feed/Header/index.module.css
- nextjs/components/Pages/Feed/Header/index.tsx
- nextjs/components/icons/PinIcon/index.module.scss
- nextjs/components/icons/PinIcon/index.tsx
- nextjs/services/channel.ts
> Pinned conversations (hidden ui)

- nextjs/components/Autocomplete/index.tsx
- nextjs/components/Pages/ChannelsPage/ChannelPage.tsx
- nextjs/components/TextInput/index.tsx
- nextjs/components/layout/PageLayout/Header/index.tsx
- nextjs/components/layout/PageLayout/index.tsx
- nextjs/components/search/SearchBar.tsx
- nextjs/utilities/colors.ts
- nextjs/utilities/util.ts
> Better header rendering for a white bg

- nextjs/__tests__/factory/response.ts
- nextjs/__tests__/pages/api/channels/index.itest.ts
- nextjs/components/Channel/NewChannelModal.tsx
- nextjs/pages/api/channels/index.ts
> Ensure that channel names are unique

- nextjs/bin/factory/account.ts
- nextjs/components/Modal/index.tsx
- nextjs/components/layout/PageLayout/Header/UserAvatar/ProfileForm/index.tsx
- nextjs/components/layout/PageLayout/Header/UserAvatar/index.tsx
- nextjs/components/layout/PageLayout/Header/index.tsx
- nextjs/components/layout/PageLayout/index.tsx
- nextjs/contexts/Join.tsx
- nextjs/pages/api/profile/index.ts
- nextjs/utilities/http.ts
> Update profile modal

- nextjs/components/Avatar/index.test.tsx
- nextjs/components/Avatar/index.tsx
> Fix avatar sizes

- nextjs/components/Actions/index.module.scss
- nextjs/components/Actions/index.tsx
- nextjs/components/Channel/Channel.tsx
- nextjs/components/Channel/ChannelGrid/index.tsx
- nextjs/components/Channel/ChannelRow/index.tsx
- nextjs/components/Channel/utilities/http.ts
- nextjs/components/Message/Row/index.tsx
- nextjs/components/Tooltip/index.module.scss
- nextjs/components/Tooltip/index.test.tsx
- nextjs/components/Tooltip/index.tsx
- nextjs/pages/api/health/index.ts
- nextjs/pages/api/merge/index.ts
https://user-images.githubusercontent.com/2088208/197182839-66e192b4-e5f3-4594-bf63-e58c46e3578e.mov
> Merge threads

- nextjs/components/Actions/index.module.scss
- nextjs/components/Channel/ChannelGrid/index.module.scss
- nextjs/components/Channel/ChannelRow/index.module.scss
- nextjs/components/Channel/PinnedThread/index.module.scss
- nextjs/components/NavBar/NavItem/index.module.scss
- nextjs/styles/colors.scss
Can't think of a better design right now, this should hopefully make it a bit easier to understand which row is pointed at when using drag & drop (admin only feature).
https://user-images.githubusercontent.com/2088208/197773470-18979dc6-8fad-4341-80a7-c8adc70ec6be.mov
> Add a drag & drop background

- nextjs/components/Channel/ChannelRow/index.module.scss
- nextjs/components/Channel/ChannelRow/index.tsx
- nextjs/components/Message/Row/index.module.scss
> Channel row footer improvements

- nextjs/components/Channel/Channel.tsx
- nextjs/components/Channel/PinnedThread/index.module.scss
- nextjs/components/Channel/PinnedThread/index.test.tsx
- nextjs/components/Channel/PinnedThread/index.tsx
- nextjs/components/Pages/Feed/Header/index.module.css
- nextjs/components/Pages/Feed/Header/index.module.scss
- nextjs/components/Pages/Feed/Header/index.tsx
> Change the UX of pinned threads

- nextjs/__tests__/pages/api/threads/[id].itest.ts
- nextjs/components/Thread/Header/Title/index.tsx
- nextjs/components/Thread/Header/index.tsx
- nextjs/components/Thread/Thread.tsx
- nextjs/pages/api/threads/[id].ts
The creator of the thread should be able to change the title and state (open/closed) of the state.
https://user-images.githubusercontent.com/2088208/198255546-51cce39d-f221-4b12-83c6-4be65c807bab.mov
> Manage own threads

- nextjs/components/Channel/Channel.tsx
- nextjs/components/Channel/Header/index.tsx
- nextjs/components/Channel/PinnedThread/index.module.scss
- nextjs/components/Channel/PinnedThread/index.test.tsx
- nextjs/components/Channel/PinnedThread/index.tsx
- nextjs/components/Channel/index.module.css
- nextjs/components/Pages/Feed/Row/Description/index.tsx
> Pinned thread improvements

- nextjs/components/Channel/ChannelGrid/index.module.scss
- nextjs/components/Channel/ChannelGrid/index.tsx
- nextjs/components/Channel/ChannelRow/index.tsx
- nextjs/components/Message/Row/index.module.scss
- nextjs/components/Message/Row/index.tsx
- nextjs/components/Pages/Feed/Row/Description/index.tsx
> Date format

- nextjs/components/Channel/Channel.tsx
- nextjs/components/Channel/ChannelGrid/index.tsx
- nextjs/components/Channel/ChannelRow/DraggableRow/index.tsx
- nextjs/components/Channel/ChannelRow/index.tsx
- nextjs/components/Channel/utilities/http.ts
- nextjs/components/Message/Row/DraggableRow/index.module.scss
- nextjs/components/Message/Row/DraggableRow/index.tsx
- nextjs/components/Message/Row/index.module.scss
- nextjs/components/Message/Row/index.tsx
- nextjs/components/Thread/Messages/index.tsx
- nextjs/components/Thread/Thread.tsx
- nextjs/components/Thread/index.module.scss
- nextjs/components/layout/shared/SidebarLayout/index.module.scss
- nextjs/components/layout/shared/SidebarLayout/index.tsx
- nextjs/hooks/mode.tsx
- nextjs/pages/api/move/index.ts
Still not 100% sure on the future of the drag and drop feature so pushing a prototype for internal testing.
https://user-images.githubusercontent.com/2088208/198997398-3bf85ea1-978d-4baa-a5e5-d73bacaafbd8.mov
> Drag messages to threads

- nextjs/__tests__/pages/api/move/thread/channel/index.itest.ts
- nextjs/pages/api/move/thread/channel/index.ts
https://user-images.githubusercontent.com/2088208/199723147-21349439-9e64-4a57-a65b-e84aff6434f1.mov
> As an owner, I can move a thread to a channel

- nextjs/components/Message/Row/index.tsx
- nextjs/pages/api/move/message/channel/index.ts
- nextjs/pages/api/move/message/thread/index.ts
https://user-images.githubusercontent.com/2088208/199760311-83b0b5a3-6d6c-4031-b67e-66c21d1c0e2f.mov
> Owner can move messages to a thread or channel

- nextjs/pages/faq/index.tsx
> Add a simple faq page

- nextjs/components/Field/index.tsx
- nextjs/components/MessageForm/index.tsx
- nextjs/components/layout/PageLayout/Header/UserAvatar/ProfileForm/AvatarField/index.module.scss
- nextjs/components/layout/PageLayout/Header/UserAvatar/ProfileForm/AvatarField/index.tsx
- nextjs/components/layout/PageLayout/Header/UserAvatar/ProfileForm/index.tsx
- nextjs/components/layout/PageLayout/Header/UserAvatar/index.tsx
- nextjs/components/layout/PageLayout/Header/index.tsx
- nextjs/components/layout/PageLayout/index.tsx
- nextjs/pages/api/profile/avatar/index.ts
- nextjs/utilities/files.ts
Closes https://github.com/Linen-dev/linen.dev/issues/631
https://user-images.githubusercontent.com/2088208/200862581-62ae586d-3571-4f00-91bf-44235d8faa85.mov
- custom file size limit for avatars (they should potentially be smaller)
- nicer loading state for an avatar (e.g. animated border)
- no page reload after update (update user client side)
- better error handling
- direct s3 upload
- test coverage
- axios upload wrapper
- axios upgrade for better stack trace
> User can upload an avatar

- nextjs/components/Message/Row/index.tsx
- nextjs/components/Pages/Channel/Content/Row/index.module.scss
- nextjs/components/Pages/Channel/Content/Row/index.tsx
- nextjs/components/layout/PageLayout/Header/UserAvatar/ProfileForm/AvatarField/index.module.scss
- nextjs/components/layout/PageLayout/Header/UserAvatar/ProfileForm/AvatarField/index.tsx
Really not 100% sure on the best design here, showing the title above the thread should make the title more useful than it is right now.
> Title channel view

- nextjs/bin/factory/account.ts
- nextjs/components/JoinButton/JoinDiscord/index.tsx
- nextjs/components/JoinButton/JoinLinen/index.tsx
- nextjs/components/JoinButton/JoinSlack/index.tsx
- nextjs/components/Modal/index.module.scss
- nextjs/components/Modal/index.tsx
- nextjs/components/NavBar/index.tsx
- nextjs/components/layout/PageLayout/Header/MobileMenu/index.module.scss
- nextjs/components/layout/PageLayout/Header/MobileMenu/index.tsx
- nextjs/components/layout/PageLayout/Header/index.tsx
- nextjs/components/layout/PageLayout/index.tsx
- nextjs/components/layout/shared/SidebarLayout/index.tsx
- nextjs/pages/community/index.tsx
- nextjs/pages/index.tsx
Mobile space is very limited, so let's experiment with a more classic mobile menu design.
Please note that we'd need to figure out how to manage search/profile and settings if we decide to use this long term.
https://user-images.githubusercontent.com/2088208/201319587-a865e6bc-52de-4c52-9b1e-5c874fe7ee13.mov
> New mobile nav

- nextjs/components/Pages/Channel/ChannelForBots.tsx
- nextjs/components/Pages/Channel/Content/index.tsx
- nextjs/components/Pages/Channel/index.tsx
- nextjs/components/Pages/ThreadPage/ThreadPage.tsx
- nextjs/lib/channel.ts
- nextjs/lib/sitemap.ts
- nextjs/lib/threads.ts
- nextjs/serializers/message.ts
- nextjs/services/channel.ts
- nextjs/services/threads.ts
- nextjs/types/apiResponses/threads/[threadId].d.ts
- nextjs/utilities/redirects.ts
- nextjs/utilities/sitemap.ts
- channel view will show the latest 30 messages, without pagination (prev and next was removed)
- thread view will have a link to next and prev thread (this will allow the crawlers to crawl the whole channel)
- channels pages was removed, access the channel with a page on the pathParams will redirect to channel's first page
> improve views for crawlers

- nextjs/components/Thread/Thread.tsx
- nextjs/pages/api/threads/[id].ts
- nextjs/prisma/migrations/20221114190209_metrics_for_support/migration.sql
- nextjs/prisma/schema.prisma
- nextjs/serializers/thread.ts
- nextjs/services/events/eventNewMessage.ts
- nextjs/services/threads.ts
new fields to allow us to make reports
closeAt             BigInt?
firstUserReplyAt    BigInt?
firstManagerReplyAt BigInt?
> Metrics support questions

- apps/web/bin/factory/messages.ts
- apps/web/components/Actions/index.module.scss
- apps/web/components/Actions/index.tsx
- apps/web/components/Message/Row/index.module.scss
- apps/web/components/Thread/index.module.scss
- apps/web/components/Tooltip/index.module.scss
- apps/web/components/Tooltip/index.tsx
- apps/web/pages/_app.tsx
- apps/web/pages/_document.tsx
This PR fixes the placement of the actions bar. It's going to be `0.5rem` lower than before, to hopefully make it easier to hover over it.
> Fix the copy url link

- apps/web/components/Pages/Feed/Grid/index.tsx
- apps/web/components/Pages/Feed/Row/Description/index.module.css
- packages/types/.gitignore
- packages/types/package.json
- packages/types/tsconfig.json
- packages/ui/package.json
- packages/ui/rollup.config.js
- packages/ui/src/Pages/Feed/Row/Description/index.module.scss
- packages/ui/src/Pages/Feed/Row/Description/index.tsx
- packages/ui/src/Pages/Feed/Row/Title/index.module.scss
- packages/ui/src/Pages/Feed/Row/Title/index.tsx
- packages/ui/src/Pages/Feed/Row/index.module.scss
- packages/ui/src/Pages/Feed/Row/index.tsx
- packages/ui/src/Pages/Feed/index.tsx
- packages/ui/tsconfig.json
- packages/ui/types.d.ts
First step in making the ui package dependent on ast, types and utilities.
> [packages/ui] add a row component

- apps/web/pages/_app.tsx
- apps/web/pages/_document.tsx
- apps/web/styles/highlight.scss
This approach should resolve the `blocking asset` issue during page rendering.
> [apps/web] inline highlight.js css

- apps/desktop/src/components/Pages/Dashboard/index.tsx
- apps/desktop/src/components/Pages/SignIn/index.tsx
- apps/desktop/src/pages/index.tsx
- apps/desktop/src/utilities/http.ts
- apps/web/api/routes.ts
- apps/web/api/routes/feed.ts
- apps/web/components/Pages/Feed/Content/index.tsx
- apps/web/components/Pages/Feed/Content/state/index.ts
- apps/web/components/Pages/Feed/Content/utilities/sendMessageWrapper.tsx
- apps/web/components/Pages/Feed/index.tsx
Moving forward with the desktop app, still tons of things to do:
- ...
> [apps/desktop] fetch data in the feed

- apps/web/components/NavBar/Desktop/index.tsx
- apps/web/components/Pages/Channel/index.tsx
- apps/web/serializers/read-status.ts
- packages/types/index.ts
Just showing a toast for now. I'd like to add the count as a next step and improve the UI.
> Read unread status toast in the channel

- apps/web/bin/factory/index.ts
- apps/web/components/Pages/Channel/index.tsx
- apps/web/components/Pages/Feed/index.tsx
- apps/web/components/Pages/Metrics/index.tsx
- apps/web/components/Pages/SignIn/index.tsx
- apps/web/pages/api/router.ts
- apps/web/pages/signin/index.tsx
- apps/web/pages/signup/index.tsx
- apps/web/services/feed/index.ts
- apps/web/utilities/auth/react/utils.ts
- packages/utilities/package.json
- packages/utilities/src/storage.spec.ts
- packages/utilities/src/storage.ts
We could keep this info in the db per community too to support the multi community use case. Keeping it in local storage for now as it requires less dev work.
> Redirect to last page (feed/metrics/channel) after sign in

- apps/desktop/src/components/Pages/Feed/Content/Thread/MessageForm/index.tsx
- apps/web/components/MessageForm/index.tsx
- apps/web/components/Pages/Channel/Content/Grid/index.module.scss
- apps/web/components/Pages/Channel/Content/Grid/index.tsx
- apps/web/components/Pages/Channel/Content/Row/Droppable/index.module.scss
- apps/web/components/Pages/Channel/Content/Row/Droppable/index.tsx
- apps/web/components/Pages/Channel/Content/Row/index.module.scss
- apps/web/components/Pages/Channel/Content/Row/index.tsx
1. title placement was incorrect
2. shift+key was producing double shits
3. hover state w/ drag and drop was buggy after recent css refactors
4. new line was hidden under the drag and drop background
> UI Bugfixes

- apps/web/.env.example
- apps/web/__tests__/pages/api/profile/index.itest.ts
- apps/web/components/Pages/Profile/index.tsx
- apps/web/components/layout/PageLayout/Header/UserAvatar/ProfileForm/index.tsx
- apps/web/components/layout/PageLayout/Header/UserAvatar/index.tsx
- apps/web/components/layout/PageLayout/Header/index.tsx
- apps/web/components/layout/PageLayout/index.tsx
- apps/web/pages/api/profile/index.ts
Closes https://github.com/Linen-dev/linen.dev/issues/814
> Display name update fixes

- apps/web/pages/communities/index.module.scss
- apps/web/pages/communities/index.tsx
- packages/ui/src/Container/index.module.scss
- packages/ui/src/Container/index.tsx
- packages/ui/src/index.tsx
> [apps/web] add a basic communities page

- apps/web/components/Pages/ThreadPage/ThreadPage.tsx
- apps/web/components/search/SearchBar.tsx
- apps/web/components/search/Suggestion/index.tsx
- apps/web/pages/api/search.ts
> Add missing user info to the search endpoint

- apps/web/components/Pages/Channel/Content/Empty/index.tsx
- apps/web/components/Pages/Channel/Content/index.tsx
Closes https://github.com/Linen-dev/linen.dev/issues/937
> [apps/web] more precise empty state for non logged in users

- apps/web/components/NavBar/Desktop/index.tsx
- apps/web/components/Pages/Channel/Content/ScrollToBottomIcon/index.module.scss
- apps/web/components/Pages/Channel/Content/ScrollToBottomIcon/index.tsx
- apps/web/components/Pages/Channel/Content/index.module.scss
- apps/web/components/Pages/Channel/Content/index.tsx
> Read unread improvements

- apps/web/components/Pages/Channel/Content/index.tsx
- apps/web/components/Pages/Channel/index.tsx
- apps/web/components/Pages/Inbox/Content/index.tsx
- apps/web/components/Thread/index.tsx
- apps/web/utilities/state/reaction.test.ts
- apps/web/utilities/state/reaction.ts
> Inbox actions

- apps/web/bin/factory/communities/ipsum/index.ts
- packages/ui/src/Dropdown/index.tsx
- packages/ui/src/Image/index.module.scss
- packages/ui/src/Image/index.tsx
> Better image error handling

- apps/web/components/Pages/Channel/index.tsx
- apps/web/components/Pages/Inbox/Content/index.tsx
Potential ui improvements:
- load a new thread to the inbox if a whole thread was removed
- add `delete thread` icon in the inbox grid
> [apps/web] add delete to the inbox

- packages/types/package.json
- packages/ui/src/Message/Link/Video/index.module.scss
- packages/ui/src/Message/Link/Video/index.tsx
- packages/ui/src/Message/Link/utilities.spec.ts
- packages/ui/src/Message/Link/utilities.ts
https://user-images.githubusercontent.com/2088208/222981182-3d9a5f32-3184-422d-b841-8af3f0b8ef9f.mov
> Support `.mov` videos

- apps/desktop/src/components/Pages/Inbox/Content/Thread/MessageForm/index.tsx
- apps/desktop/src/components/Pages/Inbox/Content/Thread/index.tsx
- apps/web/components/MessageForm/index.tsx
- apps/web/components/Pages/Channel/Content/Chat/index.tsx
- apps/web/components/Pages/Channel/index.tsx
- apps/web/components/Pages/Configurations/index.tsx
- apps/web/components/Pages/Inbox/Content/index.tsx
- apps/web/components/Pages/Inbox/Content/utilities/inbox.ts
- apps/web/components/Pages/Inbox/index.tsx
- apps/web/components/Pages/Integrations/index.tsx
- apps/web/components/Pages/Metrics/index.tsx
- apps/web/components/Pages/SignIn/index.tsx
- apps/web/components/Thread/index.tsx
- apps/web/components/layout/PageLayout/Header/UserAvatar/ProfileForm/PermissionsField/index.tsx
- apps/web/services/events/eventNewMessage.ts
- apps/web/services/messages/index.ts
- apps/web/services/user-thread-status/index.ts
- apps/web/services/webhooks/processMessageEvents.ts
- apps/web/utilities/files.ts
- apps/web/utilities/notification.ts
- packages/utilities/src/storage.spec.ts
- packages/utilities/src/storage.ts
1. Do not mark your own messages as unread
2. Increase file size limit to 2MB
3. Keep draft of msg per message form (unique per thread id / channel id / inbox)
> Improvements & bugfixes

- apps/desktop/src/components/Pages/Inbox/Content/Thread/index.module.scss
- apps/web/components/MessageForm/index.tsx
- apps/web/components/NavBar/Desktop/MenuIcon/index.module.scss
- apps/web/components/NavBar/Desktop/MenuIcon/index.tsx
- apps/web/components/NavBar/Desktop/index.module.scss
- apps/web/components/NavBar/Desktop/index.tsx
- apps/web/components/NavBar/index.spec.tsx
- apps/web/components/Thread/index.module.scss
- packages/ui/src/Layouts/Shared/SidebarLayout/index.module.scss
https://user-images.githubusercontent.com/2088208/224967955-67221113-1201-4b14-b9d8-fa70e77c80c9.mov
> cmd enter, collapsed navbar

- apps/web/components/GridRow/index.module.scss
- apps/web/components/GridRow/index.tsx
- apps/web/components/NavBar/Desktop/PoweredByLinen/index.module.scss
- apps/web/components/NavBar/Desktop/PoweredByLinen/index.tsx
- apps/web/components/NavBar/Desktop/index.tsx
- apps/web/components/Thread/Header/index.tsx
- apps/web/components/layout/PageLayout/Header/index.module.scss
- apps/web/components/layout/PageLayout/Header/index.tsx
- packages/ui/src/Badge/index.module.scss
- packages/ui/src/Badge/index.tsx
- packages/ui/src/Nav/Group/index.module.scss
- packages/ui/src/Nav/Group/index.tsx
- packages/ui/src/Nav/index.tsx
> Mobile impressions

- apps/web/components/GridRow/index.module.scss
- apps/web/components/GridRow/index.tsx
- apps/web/components/Pages/Channel/Content/Grid/index.tsx
- apps/web/components/Pages/Channel/Content/Row/Droppable/index.tsx
- apps/web/components/Pages/Channel/Content/Row/index.module.scss
- apps/web/components/Pages/Channel/Content/Row/index.tsx
- apps/web/components/Pages/Channel/Content/index.tsx
- apps/web/components/Pages/Channel/index.tsx
- apps/web/components/layout/PageLayout/Header/Logo/index.module.scss
- apps/web/components/layout/PageLayout/Header/Logo/index.tsx
- apps/web/components/layout/PageLayout/Header/index.module.scss
- apps/web/components/layout/PageLayout/Header/index.tsx
- packages/hooks/package.json
- packages/hooks/src/hover.tsx
- packages/ui/src/Avatar/index.tsx
- packages/ui/src/Code/index.tsx
- packages/ui/src/Image/utilities/preload.ts
- packages/ui/src/Message/Link/Image/index.tsx
- packages/ui/src/Message/Link/Video/index.tsx
> Performance improvements

- apps/web/components/Pages/Channel/Content/Row/index.module.scss
- apps/web/components/Pages/Channel/Content/Row/index.tsx
- packages/ui/src/Avatar/index.module.scss
- packages/ui/src/Avatars/index.module.scss
- packages/ui/src/Avatars/index.tsx
> [apps/web] optimize grid row footer

- apps/web/components/Link/JoinChannelLink/index.module.scss
- apps/web/components/Link/JoinChannelLink/index.tsx
- apps/web/components/NavBar/Desktop/ChannelsGroup/index.tsx
- apps/web/components/NavBar/Desktop/index.tsx
- apps/web/components/Pages/Channel/Content/index.module.scss
- apps/web/components/Thread/Header/index.module.scss
- apps/web/components/Thread/Header/index.tsx
- apps/web/components/Thread/index.module.scss
- apps/web/components/Thread/index.tsx
> UI experiment + powered by linen

- apps/web/components/Auth/Error.tsx
- apps/web/components/Auth/index.tsx
- apps/web/components/JoinButton/JoinDiscord/index.tsx
- apps/web/components/JoinButton/JoinLinen/index.module.css
- apps/web/components/JoinButton/JoinLinen/index.tsx
- apps/web/components/JoinButton/JoinSlack/index.tsx
- apps/web/components/JoinButton/Link/index.module.scss
- apps/web/components/JoinButton/Link/index.tsx
- apps/web/components/JoinButton/index.tsx
- apps/web/components/Pages/SignIn/index.tsx
- apps/web/components/layout/PageLayout/Header/index.tsx
> Simplify join buttons

- packages/ui/package.json
- packages/ui/src/Message/Emoji/index.tsx
- packages/ui/src/Message/Text/index.tsx
- yarn.lock
> Do not render unnecessary spans around emojis

- apps/web/components/Pages/Plans/ActivePlan/index.module.scss
- apps/web/components/Pages/Plans/ActivePlan/index.tsx
- apps/web/components/Pages/Plans/index.tsx
- apps/web/components/Table/index.tsx
- apps/web/pages/api/subscriptions/index.ts
> Change payment info

- apps/web/components/ColorInput/index.module.css
- apps/web/components/ColorInput/index.module.scss
- apps/web/components/ColorInput/index.tsx
- apps/web/components/Pages/Branding/LogoField/index.tsx
- apps/web/components/Pages/Branding/index.tsx
Branding page font sizes were a bit off versus other labels in the app. The color input styling had an unnecessary padding too. These minor changes should hopefully make the page friendlier.
Before:
After:
> [apps/web] minor UI improvements of the branding page

- apps/web/components/Footer/index.tsx
- apps/web/components/MessageForm/index.tsx
- apps/web/components/Pages/Inbox/Content/AddThreadModal/index.module.scss
- apps/web/components/Pages/Inbox/Content/AddThreadModal/index.tsx
- apps/web/components/Pages/Inbox/Content/AddThreadModal/utilities/message.ts
- apps/web/components/Pages/Inbox/Content/index.tsx
- apps/web/components/layout/PageLayout/Header/MobileMenu/index.module.scss
- apps/web/components/layout/PageLayout/Header/MobileMenu/index.tsx
- apps/web/mailers/views/layouts/default.ts
- apps/web/pages/_app.tsx
- apps/web/pages/index.tsx
- packages/ui/src/Modal/index.module.scss
- packages/ui/src/Pages/Inbox/Grid/index.tsx
- packages/ui/src/Pages/Inbox/Row/Actions/index.tsx
- packages/ui/src/Pages/Inbox/Row/index.tsx
> Preview mode

- README.md
> readme.md: Fix spelling of 'impressions'.

- apps/web/components/layout/BlankLayout/index.tsx
- apps/web/components/layout/CardLayout/index.tsx
- apps/web/components/layout/PageLayout/index.tsx
- apps/web/components/layout/SplitLayout/index.tsx
- packages/ui/src/Modal/index.tsx
- packages/ui/src/NavBar/Desktop/AddCommunityLink/index.tsx
- packages/ui/src/Portal/index.tsx
- packages/ui/src/Tooltip/index.module.scss
- packages/ui/src/Tooltip/index.tsx
This should hopefully make it more explicit on what the plus button does.
> Create New Community tooltip

- apps/web/components/Pages/GettingStartedPage/index.tsx
- apps/web/components/Pages/Onboarding/index.module.scss
- apps/web/components/Pages/Onboarding/index.tsx
> Onboarding improvements

- apps/web/components/Pages/GettingStartedPage/index.module.scss
- apps/web/components/Pages/GettingStartedPage/index.tsx
- packages/ui/src/Button/index.module.scss
> Add a second call to action in the getting started page

- apps/web/bin/factory/communities/dolor/index.ts
- apps/web/bin/factory/communities/sit/index.ts
- apps/web/bin/factory/index.ts
- apps/web/components/layout/PageLayout/index.module.scss
- apps/web/components/layout/PageLayout/index.tsx
- apps/web/pages/communities/index.module.scss
- apps/web/pages/communities/index.tsx
- packages/styles/globals.css
- packages/ui/src/Layouts/Shared/SidebarLayout/index.module.scss
- packages/ui/src/MessageForm/index.tsx
- packages/ui/src/TextInput/index.module.scss
- packages/ui/src/TextInput/index.tsx
- packages/ui/src/Thread/index.module.scss
- packages/utilities/src/storage.spec.ts
- packages/utilities/src/storage.ts
- adding styles rounded input  and using it on the communities page, similar styling is going to be used in the getting-started page
- improving the db seed with 2 blank communities
- refactoring page layout styles to hopefully fix a safari mobile bug
- nicer global scroll bar
- hydration fix for drafts
- mobile fix around viewport width at 320px
> Getting started improvements

- apps/web/components/Pages/Channel/index.tsx
- packages/spa/src/pages/Channel.tsx
- packages/ui/src/AllView/Empty/index.module.scss
- packages/ui/src/ChannelView/Content/Empty/index.module.scss
- packages/ui/src/ChannelView/Content/Empty/index.tsx
- packages/ui/src/ChannelView/Content/index.tsx
- packages/ui/src/ChannelView/index.tsx
- packages/ui/src/InboxView/Empty/index.module.scss
- packages/ui/src/StarredView/Empty/index.module.scss
> Add call to actions in the empty state of a channel

- packages/ui/src/ChannelView/Content/Empty/index.module.scss
- packages/ui/src/ChannelView/Content/Empty/index.tsx
> Improve the empty state

- apps/web/pages/communities/index.module.scss
- apps/web/pages/communities/index.tsx
- packages/ui/src/Autocomplete/index.module.scss
- packages/ui/src/Autocomplete/index.tsx
- packages/ui/src/Modal/index.module.scss
- packages/ui/src/NavBar/Desktop/FindCommunityLink/index.module.scss
- packages/ui/src/NavBar/Desktop/FindCommunityLink/index.tsx
- packages/ui/src/NavBar/Desktop/index.tsx
- packages/ui/src/Pages/Styleguide/examples/TextInput.tsx
> Minor improvements

- packages/ui/src/AddThreadModal/index.module.scss
- packages/ui/src/AddThreadModal/index.tsx
- packages/ui/src/EditMessageModal/index.module.scss
- packages/ui/src/EditMessageModal/index.tsx
- packages/ui/src/EditThreadModal/index.module.scss
- packages/ui/src/EditThreadModal/index.tsx
- packages/ui/src/Header/MobileMenu/index.tsx
- packages/ui/src/Modal/index.module.scss
- packages/ui/src/Modal/index.tsx
> Edit message in a modal

- apps/web/components/layout/PageLayout/index.tsx
- packages/spa/src/components/NavLeftBar/index.tsx
- packages/ui/src/Header/index.module.scss
- packages/ui/src/Header/index.tsx
- packages/ui/src/NavBar/Desktop/index.tsx
- packages/ui/src/NavBar/index.tsx
1. We'd like to be able to ignore the notification.
2. The notification should disappear when you click on the channel
3. The notification should not show up if you're already in the channel
4. Fixing a highlighting bug when you're already in the channel and you get a mention
> Better mention handling

- packages/ui/src/GridRow/index.module.scss
- packages/ui/src/GridRow/index.tsx
- packages/ui/src/MessagePreview/index.module.scss
- packages/ui/src/Row/index.tsx
> Bring back the open closed check

- apps/web/pages/_app.tsx
- packages/spa/src/App.tsx
- packages/ui/src/Header/index.tsx
- packages/ui/src/NavBar/Desktop/index.module.scss
- packages/ui/src/NavBar/Desktop/index.tsx
- packages/ui/src/Toast/index.module.scss
- packages/ui/src/Toast/index.tsx
> Improve styling of the toast

- apps/web/components/layout/PageLayout/ErrorFallback/index.module.scss
- apps/web/components/layout/PageLayout/index.module.scss
- apps/web/pages/communities/index.module.scss
- packages/spa/src-tauri/Cargo.toml
- packages/spa/src-tauri/tauri.conf.json
- packages/spa/src/components/Layout/index.module.scss
- packages/spa/src/components/NavTopBar/index.module.scss
- packages/spa/src/components/NavTopBar/index.tsx
- packages/spa/src/components/TitleBar/index.module.scss
- packages/spa/src/components/TitleBar/index.tsx
- packages/spa/src/di/tauri/index.ts
- packages/spa/src/di/types.ts
- packages/spa/src/di/web/index.ts
- packages/spa/src/index.tsx
- packages/styles/desktop.css
- packages/styles/globals.css
- packages/styles/package.json
- packages/ui/src/Autocomplete/index.module.scss
- packages/ui/src/BrandingView/index.module.scss
- packages/ui/src/Header/index.module.scss
- packages/ui/src/Header/index.tsx
- packages/ui/src/MembersView/index.module.scss
- packages/ui/src/MetricsView/index.module.scss
- packages/ui/src/Modal/index.module.scss
- packages/ui/src/NavBar/Desktop/index.module.scss
- packages/ui/src/SplitLayout/index.module.scss
- packages/ui/src/Thread/index.module.scss
- packages/utilities/src/storage.spec.ts
- packages/utilities/src/storage.ts
We can make it better for sure and play with the styling, taking the minimalistic approach for now so we can release the client asap.
> Linen desktop header

- apps/web/pages/_app.tsx
- packages/ui/src/Actions/index.tsx
- packages/ui/src/ChannelView/ForumView/index.tsx
- packages/ui/src/ForumRow/index.module.scss
- packages/ui/src/ForumRow/index.tsx
- packages/ui/src/GridRow/index.tsx
- packages/ui/src/Row/index.module.scss
- packages/ui/src/Row/index.tsx
Closes https://github.com/Linen-dev/linen.dev/issues/1274
> Forum view improvements

- apps/web/bin/factory/communities/dolor/index.ts
- apps/web/bin/factory/communities/ipsum/index.ts
- apps/web/bin/factory/communities/linen/index.ts
- apps/web/bin/factory/communities/sit/index.ts
- packages/ui/src/NavBar/Desktop/index.module.scss
- packages/ui/src/NavBar/Desktop/index.tsx
- packages/ui/src/Row/index.module.scss
- packages/ui/src/Row/index.tsx
- packages/ui/src/Row/utilities/mentions.ts
- packages/ui/src/Toast/index.tsx
To reduce complexity, I've extended the info section in the bottom to include the mentions information. The animation was more complicated.
> Visually identify mention

- apps/push_service/README.md
> [apps/push_service] fix typo in README.md

- apps/web/pages/index.tsx
> update the section background color

- apps/web/bin/factory/communities/dolor/index.ts
- apps/web/bin/factory/communities/ipsum/index.ts
- apps/web/bin/factory/communities/linen/index.ts
- apps/web/bin/factory/communities/sit/index.ts
- apps/web/components/Pages/GettingStartedPage/index.tsx
- apps/web/contexts/Join.tsx
- apps/web/pages/invite/[communityName]/index.module.scss
- apps/web/pages/invite/[communityName]/index.tsx
- apps/web/services/invites.ts
- apps/web/services/permissions/index.ts
- packages/types/src/index.ts
- packages/ui/src/BlankLayout/index.tsx
- packages/ui/src/Button/index.module.scss
- packages/ui/src/Button/index.tsx
- packages/ui/src/Card/index.tsx
- packages/ui/src/ChannelView/ChatView/index.tsx
- packages/ui/src/ChannelView/ForumView/index.tsx
- packages/ui/src/ChannelView/index.tsx
- packages/ui/src/CommunityCard/index.tsx
- packages/utilities/package.json
- packages/utilities/src/number.ts
Instead of linking to the community itself, we can link to an invite page, which will be a bit more explicit for first time users.
> Invite page

- packages/ui/src/MembersView/index.tsx
- packages/utilities/package.json
- packages/utilities/src/email.spec.ts
- packages/utilities/src/email.ts
**Issue number :- #1315**
_**Expected output video:-**_
> fix email validation and optimization API call

- apps/web/pages/api/feed/index.tsx
- apps/web/pages/feed/index.module.scss
- apps/web/pages/feed/index.tsx
- apps/web/services/feed/index.ts
- packages/ui/src/Message/Emoji/utilities/emojis.json
Experimenting with showing communities in the right. We might want to show them with most interesting threads below.
Mobile view not included in this PR.
> Feed communities

- apps/web/pages/feed/index.module.scss
- apps/web/pages/feed/index.tsx
- packages/ui/src/ForumRow/index.module.scss
- packages/ui/src/Modal/index.module.scss
- packages/ui/src/Modal/index.tsx
- packages/ui/src/Row/index.module.scss
- packages/ui/src/Row/index.tsx
- packages/utilities/src/date.test.ts
- packages/utilities/src/date.ts
1. timeAgo in the feed
2. mobile navigation in the feed
3. truncation for long messages (feed and chat view)
4. fixing an overflow bug in the forum view
> Feed improvements

- packages/ui/src/ProfileForm/AvatarField/index.tsx
> Fixed avatar image input validation

- apps/web/bin/factory/communities/linen/index.ts
- apps/web/pages/feed/index.module.scss
- apps/web/pages/feed/index.tsx
- packages/ui/package.json
- packages/ui/src/Image/index.tsx
- packages/ui/src/InboxView/index.tsx
- packages/ui/src/Preview/index.tsx
- packages/ui/src/RowSkeleton/index.module.scss
- packages/ui/src/RowSkeleton/index.tsx
- yarn.lock
Super quick skeleton for better pagination, not very precise as of sizing yet.
> Feed skeleton

- apps/web/components/Pages/Channels/index.tsx
- apps/web/components/layout/PageLayout/index.tsx
- apps/web/services/ssr/channels.ts
- packages/ui/src/ChannelsView/index.module.scss
- packages/ui/src/ChannelsView/index.tsx
- packages/ui/src/ConfigurationsView/CommunityTypeRow/index.tsx
- packages/utilities/src/array.test.ts
- packages/utilities/src/array.ts
> Improve channel settings

- packages/ast/parse/slack/index.js
- packages/ast/parse/slack/index.spec.js
> Improve the slack emoji regexp

- apps/web/bin/factory/communities/linen/index.ts
- apps/web/pages/api/inbox/index.ts
- apps/web/pages/api/user-thread-status/index.ts
- apps/web/queue/jobs.ts
- apps/web/services/user-thread-status/index.ts
- packages/queue/src/index.ts
- packages/queue/src/tasks/cleanup-user-thread-status.ts
- packages/queue/src/tasks/mark-all-as-read.ts
- packages/ui/src/InboxView/index.tsx
User thread status table is getting to big, so we're going to narrow down the statuses to the last 60 days.
> User thread statuses improvements

- dev/slackApp/sampleAppManifest.yml
- docs/slack-app.md
> docs(slack): :memo: Update slack app docs

- apps/web/components/layout/PageLayout/ErrorFallback/index.module.scss
- apps/web/components/layout/PageLayout/index.module.scss
- apps/web/pages/invite/[communityName]/index.module.scss
- packages/spa/src/components/Layout/index.module.scss
- packages/ui/src/Autocomplete/index.module.scss
- packages/ui/src/BrandingView/index.module.scss
- packages/ui/src/MembersView/index.module.scss
- packages/ui/src/MetricsView/index.module.scss
- packages/ui/src/Modal/index.module.scss
- packages/ui/src/NavBar/Desktop/index.module.scss
- packages/ui/src/SplitLayout/index.module.scss
- packages/ui/src/Thread/index.module.scss
dvh is available since chrome 108: [https://caniuse.com/?search=dvh](https://caniuse.com/?search=dvh)
vh is available since chrome 26: https://caniuse.com/?search=vh
> Use vh for desktop and dvh for mobile to support a wider range of browsers

- packages/ui/src/Code/index.tsx
- packages/ui/src/Message/BlockCode/index.module.scss
- packages/ui/src/Message/BlockCode/index.tsx
- packages/ui/src/Message/InlineCode/index.tsx
> Add a copy code label

- apps/web/components/layout/PageLayout/index.tsx
- packages/ui/package.json
- packages/ui/src/Avatar/index.module.scss
- packages/ui/src/Avatar/index.tsx
- packages/ui/src/Button/index.tsx
- packages/ui/src/GridRow/index.tsx
- packages/ui/src/NavBar/Desktop/DMs/index.tsx
- packages/ui/src/NavBar/Desktop/index.tsx
- packages/ui/src/NavBar/index.spec.tsx
- packages/ui/src/NavBar/index.tsx
- packages/ui/src/NewDmModal/index.tsx
- packages/ui/src/UserModal/index.module.scss
- packages/ui/src/UserModal/index.tsx
- packages/utilities/src/event.js
> User profile modal

- apps/web/components/Pages/Channel/index.tsx
- apps/web/components/layout/PageLayout/index.tsx
- packages/ui/src/ChannelView/TopicView/Grid/index.tsx
- packages/ui/src/ChannelView/TopicView/index.tsx
- packages/ui/src/NavBar/Desktop/ChannelsGroup/RecentTopics/index.module.scss
- packages/ui/src/NavBar/Desktop/ChannelsGroup/RecentTopics/index.tsx
- packages/ui/src/NavBar/Desktop/ChannelsGroup/RecentTopics/utilities/topics.ts
- packages/ui/src/NavBar/Desktop/ChannelsGroup/index.tsx
- packages/ui/src/NavBar/Desktop/index.tsx
- packages/ui/src/NavBar/index.tsx
> Recent threads sidebar
